# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via Aleksandr Hovhannisyan, , and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via .
title: Kryton
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Electronics, Technology projects & Baking
baseurl: "" # the subpath of your site, e.g. /blog
url: "stuff.kryton.me.uk" # the base hostname & protocol for your site, e.g. http://example.com
# also change CNAME file!
github_username:  kryton-me

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
plugins: 
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# defaults for pages

defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: default
